import type { Metadata } from "next";
import { Geist, Geist_Mono, Jura } from "next/font/google";
import { Winky_Rough } from "next/font/google";
import "./globals.css";

const jura = Jura({
  variable: "--font-jura",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const winkyRough = Winky_Rough({
  variable: "--font-winky-rough",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jura.variable} ${geistSans.variable} ${geistMono.variable} ${winkyRough.variable} antialiased leading-relaxed text-white font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
